<?php
/**
 * @file
 * Code for the Cookie monster feature.
 */

include_once 'cookie_monster.features.inc';

/**
 *  Implements hook_menu().
 */
function cookie_monster_menu() {
  $items = array();

  $items['cookies'] = array(
    'title' => 'Cookie monster cookies',
    'page callback' => 'cookie_monster_cookies',
    'access arguments' => array('view all cookies'),
  );

  $items['cookies/add'] = array(
    'title' => 'Add cookies',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cookie_monster_add_cookies'),
    'access arguments' => array('add cookies'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items['cookies/get_jars'] = array(
    'page callback' => 'cookie_monster_get_jars_autocomplete',
    'access callback' => TRUE,
  );

  $items['cookies/delete_cookie/%node/%'] = array(
    'page callback' => 'cookie_monster_delete_cookie',
    'page arguments' => array(2, 3),
    'access arguments' => array('delete cookies'),
  );

  return $items;
}

/**
 *  Implements hook_permission().
 */
function cookie_monster_permission() {
  return array(
    'view all cookies' => array(
      'title' => t('View all cookies'),
      'description' => t('Determine who can see all the cookies of cookie monster'),
    ),
    'add cookies' => array(
      'title' => t('Add cookies'),
      'description' => t('Grant to the user the option to add cookies to the jar'),
    ),
    'delete cookies' => array(
      'title' => t('Delete cookie'),
      'description' => t('Allow user to delete cookie'),
    ),
  );
}

/**
 * Get all the cookies.
 *
 * @param bool $return_query
 *   Determine if the function should return the query before executing.
 *
 * @return array | EntityFieldQuery
 *   The query object or the executed value of the query.
 */
function cookies_monster_get_cookies($return_query = FALSE) {
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'cookies');

  return $return_query ? $query : $query->execute();
}

/**
 * Get all the cookies.
 */
function cookie_monster_get_jars() {
  $results = cookies_monster_get_cookies();

  if (empty($results['node'])) {
    return array();
  }

  return _cookie_monster_get_jars(array_keys($results['node']));
}

/**
 * Return autocomplete of jars.
 */
function cookie_monster_get_jars_autocomplete($string = '') {

  $query = cookies_monster_get_cookies(TRUE);

  $results = $query
    ->fieldCondition('body', 'value', $string, 'CONTAINS')
    ->execute();

  drupal_json_output(_cookie_monster_get_jars(array_keys($results['node'])));
}

/**
 * Construct a list of jars from the nodes.
 *
 * @param $nodes
 *   List of nodes.
 *
 * @return array
 *   All the and their title.
 */
function _cookie_monster_get_jars($nodes) {
  $return = array();

  foreach ($nodes as $node) {
    $wrapper = entity_metadata_wrapper('node', $node);
    $value = check_plain(strip_tags($wrapper->body->value->value()));
    $value = trim(preg_replace('/\s\s+/', ' ', $value));
    $return[$value] = $value;
  }

  return array_unique($return);
}

/**
 * Page callback; Show all cookie monster cookies.
 */
function cookie_monster_cookies() {
  drupal_add_library('system', 'drupal.ajax');

  $content = '';
  $content .= '<h2>This is cookie monster cookies:</h1>';

  $headers = array(t('Title'), t('Description'), t('Amount'), t('Operations'));

  $results = cookies_monster_get_cookies();


  if (!empty($results['node'])) {
    $nodes = node_load_multiple(array_keys($results['node']));

    foreach ($nodes as $node) {
      $wrapper = entity_metadata_wrapper('node', $node);
      $items = array(
        l(t('Edit'), 'node/' . $node->nid . '/edit'),
        l(t('Delete'), 'cookies/delete_cookie/' . $node->nid . '/nojs', array('attributes' => array('class' => 'use-ajax'))),
      );
      $rows[] = array(
        'data' => array(
          $wrapper->label(),
          $wrapper->body->value->value(),
          $wrapper->field_amount->value(),
          theme('item_list', array('items' => $items, 'attributes' => array('class' => array('list-inline'))))
        ),
        'class' => array('cookie-' . $node->nid),
      );
    }
  }
  else {
    $rows[] = array(
      array(
        'data' => t('Where are all the cookies? <a href="@link">Add cookie!</a>', array('@link' => url('cookies/add'))),
        'colspan' => '4',
        'class' => 'text-center',
      ),
    );
  }

  $content .= theme('table', array('header' => $headers, 'rows' => $rows));

  return $content;
}

/**
 * Add cookies to the jar!
 */
function cookie_monster_add_cookies($form, $form_state) {
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#required' => TRUE,
  );

  $form['amount'] = array(
    '#type' => 'textfield',
    '#title' => t('Amount'),
    '#description' => t('How many cookies of that one you have in the jar?'),
    '#required' => TRUE,
    '#element_validate' => array('element_validate_integer'),
  );

  $form['populate'] = array(
    '#type' => 'radios',
    '#title' => t('Cookie jar population way'),
    '#description' => t('How you want to get the cookies type?'),
    '#options' => array(
      'auto' => t('Auto complete'),
      'list' => t('Select list'),
    ),
    '#default_value' => 'auto',
  );

  $form['cookies_list'] = array(
    '#type' => 'select',
    '#title' => t('Cookies jars'),
    '#options' => cookie_monster_get_jars(),
    '#states' => array(
      'visible' => array(
        ':input[name="populate"]' => array('value' => 'list'),
      ),
    ),
  );

  $form['cookies_free'] = array(
    '#type' => 'textfield',
    '#title' => t('Free typing'),
    '#states' => array(
      'invisible' => array(
        ':input[name="populate"]' => array('value' => 'list'),
      ),
    ),
    '#autocomplete_path' => 'cookies/get_jars',
  );

  $form['howmany_emails'] = array(
    '#type' => 'select',
    '#title' => t('Add email'),
    '#options' => array(1, 2, 3, 4, 5),
    '#ajax' => array(
      'callback' => 'cookie_monster_add_more_email',
      'wrapper' => 'cookie-emails',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  $form['emails'] = array(
    '#type' => 'fieldset',
    '#title' => t('Emails'),
    '#prefix' => '<div id="cookie-emails">',
    '#suffix' => '</div>',
  );

  $num_checkboxes = !empty($form_state['values']['howmany_emails']) ? $form_state['values']['howmany_emails'] + 1 : 1;

  for ($i = 1; $i <= $num_checkboxes; $i++) {
    $form['emails']['emails_' . $i] = array(
      '#type' => 'textfield',
      '#title' => t('Email #@number', array('@number' => $i)),
    );
  }

  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    ),
  );

  return $form;
}

function cookie_monster_add_more_email($form, $form_state) {
  return $form['emails'];
}

/**
 * Validate handler.
 */
function cookie_monster_add_cookies_validate($form, $form_state) {
  $key = $form_state['values']['populate'] == 'auto' ? 'cookies_free' : 'cookies_list';
  if (empty($form_state['values'][$key])) {
    form_set_error($key, t('You need to populate cookies!'));
  }
}

/**
 * Submit handler.
 */
function cookie_monster_add_cookies_submit($form, &$form_state) {
  $values = $form_state['values'];
  $key = $form_state['values']['populate'] == 'auto' ? 'cookies_free' : 'cookies_list';

  $node = entity_create('node', array(
    'type' => 'cookies',
  ));

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->title->set($values['title']);
  $wrapper->field_amount->set($values['amount']);
  $wrapper->body->set(array('value' => $values[$key], 'format' => 'full_html'));
  $wrapper->save();

  $form_state['redirect'] = 'cookies';

  foreach ($values as $key => $email) {
    if (strpos($key, 'emails_') === FALSE) {
      continue;
    }

    if (!$email) {
      continue;
    }

    drupal_set_message('Sending email to '. $email);
  }
}

/**
 * Delete cookie. Via ajax!
 */
function cookie_monster_delete_cookie($node, $ajax = 'nojs') {
  node_delete($node->nid);
  $message = t('%title has been removed', array('%title' => $node->title));

  if ($ajax === 'ajax') {
    $message = '<tr><td colspan=4 class="text-center alert-success">' . $message . '</td></tr>';
    $commands[] = ajax_command_replace(".cookie-" . $node->nid, $message);
    $page = array('#type' => 'ajax', '#commands' => $commands);
    ajax_deliver($page);
  }
  else {
    // In case we don't have js.
    drupal_set_message($message);
    drupal_goto('cookies');
  }
}
